pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["areas.htm","Áreas","Áreas Top Previous Next Se gestionan las áreas de producción desde donde se pueden rechazar cascos. ",""],
["causas_de_rechazo.htm","Causas de Rechazo","Causas de Rechazo Top Previous Next Se especifican las causas por las cuales se pueden rechazar los cascos ",""],
["chapter_2.htm","Chapter 2","Chapter 2 Top Previous Next Enter topic text here. ",""],
["clientes.htm","Clientes","Clientes Top Previous Next Se gestionan los clientes y la información del contrato. El campo Externo se marca para los clientes que son otras reca...",""],
["comercial.htm","Comercial","Comercial Top Previous Next ",""],
["devolucion_a_inservibles.htm","Devolución a inservibles","Devolución a inservibles Top Previous Next Los cascos que entran al proceso de producción y se detecta algun problema por el cual no pueden ser pr...",""],
["devolucion_a_vulca.htm","Devolución a vulca","Devolución a vulca Top Previous Next Al salvar los datos se presenta la pantalla con los datos captados y la opción para adicionar los cascos que ...",""],
["elementos_graficos.htm","Elementos gráficos","Elementos gráficos Top Previous Next Iconos Añadir un nuevo elemento Editar un elemento Eliminar un elemento Botones Adicionar un elemento Editar ...",""],
["empresa.htm","Empresa","Empresa Top Previous Next Se captan los datos de la Empresa recapadora donde se instala este sistema. ",""],
["entradas.htm","Entradas","Entradas Top Previous Next Operaciones que recepcionan cascos ",""],
["entregar_a_produccion.htm","Entregar a Producción","Entregar a Producción Top Previous Next Se registran los documentos mediante los cuales se entregan cascos al proceso de producción. Al salvar los...",""],
["entregar_a_produccion_terminad.htm","Entregar a producción terminada","Entregar a producción terminada Top Previous Next ",""],
["entregar_rechazados.htm","Entregar rechazados","Entregar rechazados Top Previous Next Se realiza la entrega al cliente de los cascos rechazados tanto por producción como por error de revisión. A...",""],
["especificaciones.htm","Especificaciones","Especificaciones Top Previous Next ",""],
["estructura_general_del_diseno.htm","Estructura general del diseño","Estructura general del diseño Top Previous Next ",""],
["facturas.htm","Facturas","Facturas Top Previous Next Se realiza la factura al cliente. El número de la factura es generado automáticamente. El Tipo Ajuste, se presentan aqu...",""],
["formas_de_pago.htm","Formas de Pago","Formas de Pago Top Previous Next Se especifican las formas de pago por las que el cliente puede efectuar un pago: Cheque, Transferncia, etc. ",""],
["grupos_de_usuarios.htm","Grupos de Usuarios","Grupos de Usuarios Top Previous Next Se crean grupos de usuarios para que se le dan los permisos para luego asociar el usuario a un grupo. Al Salv...",""],
["herramientas_de_desarrollo.htm","Herramientas de desarrollo","Herramientas de desarrollo Top Previous Next Servidor web Apache con mod_wsgi para implementación Como servidor de Base de Datos Postgres 9 Como I...",""],
["herramientas_de_desarrollo_2.htm","Casco","Herramientas de desarrollo Top Previous Next Se realizan las operaciones referentes a los cascos cuando son recepcionados y enviados a producción ",""],
["indice.htm","Índice","Índice Top Previous Next Se muestran los datos captados de la opción seleccionada en el menú principal. 1 Cantidad de filas a mostrar por páginas ...",""],
["introduction.htm","Introducción","Introducción Top Next El producto informático desarrollado (Comerciax) con el uso de la tecnología de código abierto permite: Captar la informació...",""],
["introduction_2.htm","Módulos del Sistema","Introducción Top Previous Next El producto informático desarrollado (Comerciax) con el uso de la tecnología de código abierto permite: Captar la i...",""],
["mostrar_datos.htm","Mostrar datos","Mostrar datos Top Previous Next Se muestran los datos del elemento seleccionado en le Índice, estos datos se pueden Editar para ser modificados o ...",""],
["new_topic.htm","New topic","New topic Top Previous Enter topic text here. ",""],
["numero_de_casco_x_org_.htm","Número de Casco x Org.","Número de Casco x Org. Top Previous Next Se seleccionan los organismos que tendrán una numeración de casco diferente ",""],
["ofertas.htm","Ofertas","Ofertas Top Previous Next Se realiza la oferta al cliente de los cascos que se encuentran terminados para ser facturados. El número de la oferta s...",""],
["organismos.htm","Organismos","Organismos Top Previous Next Se gestionan los organismos y las uniones. Al seleccionar la opción de salvar se presenta la pantalla que muestra los...",""],
["overview.htm","Overview","Overview Top Previous Next Enter topic text here. ",""],
["pagos.htm","Pagos","Pagos Top Previous Se registran los pagos efectuados por los clientes. El pago puede ser en Efectivo u Otros. Pago en Efectivo. Al salvar los dato...",""],
["pantalla_de_captacion.htm","Pantalla de Captación","Pantalla de Captación Top Previous Next 1 Título de la pantalla de captación 2 Descripción de la captación 3 Área de captación de datos ",""],
["pantalla_principal.htm","Pantalla principal","Pantalla principal Top Previous Next 1 Menú Principal 2 Se muestran las opciones del menú seleccionado 3 Área dónde se mustran los datos Nombre de...",""],
["plataforma_de_desarrollo.htm","Plataforma de desarrollo","Plataforma de desarrollo Top Previous Next Python 2..7.1 + Django 1.3.0 ",""],
["plataforma_de_desarrollo_2.htm","Administración","Plataforma de desarrollo Top Previous Next En este módulo se administran los datos de los clasificadores del sistema. ",""],
["produccion.htm","Producción","Producción Top Previous Next Se realizan las operaciones referentes a los cascos cuando se encuentran en le proceso de producción. ",""],
["produccion_terminada_desde_ent.htm","Producción terminada desde entidades externas","Producción terminada desde entidades externas Top Previous Next Se realiza l arecepción de producción terminada desde entidades externas, o sea, d...",""],
["productos.htm","Productos","Productos Top Previous Next Se introducen los productos ",""],
["provincias.htm","Provincias","Provincias Top Previous Next Se introducen las provincias del país. ",""],
["recepcion_a_clientes.htm","Recepción a Clientes","Recepción a Clientes Top Previous Next Se realiza la recepción de cascos a los clientes Se recepcionan los cascos que traen los clientes para ser ...",""],
["recepcion_a_clientes_ext_.htm","Recepción a Clientes Ext.","Recepción a Clientes Ext. Top Previous Next Se realiza la recepción de cascos a los clientes externos Se recpcionan los cascos de las entidades ex...",""],
["recepcion_rechazados_por_clien.htm","Recepción Rechazados por clientes externos","Recepción Rechazados por clientes externos Top Previous Next Se realiza la recepción de los cascos que se enviaron por Transferencia a otras entid...",""],
["rechazar_por_error_de_revision.htm","Rechazar por error de revisión","Rechazar por error de revisión Top Previous Next En esta opción se seleccionan aquellos cascos que en el proceso de revisión no se rechazaron y se...",""],
["salidas.htm","Salidas","Salidas Top Previous Next Operaciones que producen salidas del almacen de casco ",""],
["second_topic.htm","Second topic","Second topic Top Previous Next Enter topic text here. ",""],
["sub_chapter_2_1.htm","Sub chapter 2.1","Sub chapter 2.1 Top Previous Next Enter topic text here. ",""],
["sucursales.htm","Sucursales","Sucursales Top Previous Next Se introducen los nombres de las diferentes sucursales de pago. ",""],
["tipos_de_mensajes.htm","Tipos de mensajes","Tipos de mensajes Top Previous Next Estos mensajes serán mostrados cuando para efectuarse una operación se requiera de la confirmación del usuario...",""],
["transferencia.htm","Transferencia","Transferencia Top Previous Next Se realiza la transferencia de cascos a otras entidades externas. Al salvar los datos se presenta la pantalla con ...",""],
["unidades_de_medida.htm","Unidades de Medida","Unidades de Medida Top Previous Next Se introducen las unidades de medida que se le asignarán a los productos ",""],
["usaurios.htm","Usaurios","Adicionar usarios al sistema. La clave debe tener como minimo 6 caracteres Al Salvar los datos se presenta la pantalla que muestra los datos capta...",""],
["vulca_a_produccion.htm","Vulca a producción","Vulca a producción Top Previous Next En esta opción se seleccionan aquellos cascos que se encuentran y vulca y volverán al proceso de producción. ...",""],
["welcome_topic.htm","Welcome topic","Welcome topic Top Previous Next ",""]];
